### ISSUE TITLE
[Rosetta] Investigate Changes needed to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by aslawson** [celo-org/rosetta#141]
Blockchain is investigating making Celo's 3 extra transaction fields optional. We should have a sense of how much work needs to be done and the touchpoints for ensuring Rosetta doesn't break for transactions not including these fields.

**Comment by eelanagaraj** [comment]
summary of findings and discussion with @oneeman 

_The old Construction API (`/master`) -- still looking into this_
- this version's submit tx function uses ethClient.SendRawTransaction (CallContext with eth_sendRawTransaction ) under the hood; it takes in a raw RLP-encoded signed tx
- this probably means no changes for the Rosetta implementation, but it'll be important to communicate this to users of this version so that they add the necessary `EthCompatible` field to the RLP-encoded TX that they submit to the endpoint (waiting for confirmation on this -- will update when that's done)

_The new Construction API (`/beta/construction`) should not be effected too much by the changes._ 
- Constructing txs is always done at the tip of the blockchain (no need to worry about addressing different `Transaction` object structures depending on blocknumber, etc.)
- Rosetta running on an older blockchain version would still be able to submit transactions to the chain after the 3 fields are made optional.
- Upgrading Rosetta's internal blockchain node would require us to add the `EthCompatible` field to the `Transaction` object we construct; for how Rosetta is being used, it's should (most likely) default to `EthCompatible=False`. This should be extremely minor work for the new version of the construction API (`beta/construction`), should be testable via the same methods as before (Construction tests that already exist)

_The Data API (`/master`) should be fine; we may need to make some changes when upgrading Rosetta's blockchain version._
- the Data API reads chain data to perform account reconciliation and return tx info per block
- From chatting with Or, there shouldn't be any backwards compatibility issues here (i.e. Rosetta as is should perform reads of the blockchain properly, even after the additional `EthCompatible` field is added; optional fields will still be on the `Transaction` object)
- once we upgrade Rosetta, we may need to apply the additional `EthCompatible=False` default setting for past/future reads to fix simple compilation errors; no clear reason to make `EthCompatible=True` txs within Rosetta.
