### ISSUE TITLE
[Rosetta] Implement changes needed to support optional 3 extra transaction fields

### ISSUE THREAD

**Issue by aslawson** [celo-org/rosetta#144]
Implement changes from #141 to support removing 3 extra fields

https://www.notion.so/clabsco/Explore-tool-changes-due-to-ethereum-format-transactions-75fb18b535664885a1da07df7169122b

**Comment by eelanagaraj** [comment]
I spent some time looking into this last week -- the changes themselves still shouldn't take a lot of time, however on second look, it probably makes most sense to bundle this work with donut modifications. The reason is that the PR including these changes already includes a lot of those changes, esp. a renaming of the modules (go-ethereum -> celo-blockchain) that basically wreaks havoc on kliento + deps in rosetta. (I.e. will require modifications to kliento + rosetta just to import properly).

**Comment by eelanagaraj** [comment]
@aslawson @barbaraliau Comment above has more details ^^ but maybe it makes sense for the next sprint to expanding the scope to all donut changes? (i.e. probably makes sense to bundle these tasks together:
- PR for renaming modules in kliento
- updating rosetta to include this, then renaming the modules incl. blockchain in rosetta
- then the work scoped in this ticket (adding support for the three tickets) + any necessary changes from donut, in order to get stuff compiling + testable
wdyt?

**Comment by eelanagaraj** [comment]
## Update:

### Summary:

The precompiles (CIP 20, 25, 26), BLS Curve Operations changes (CIP 30, 31), Epoch Snark Data (CIP 22), and Governable Lookback Window (CIP 21) shouldn't have any impact on rosetta. CIP 28 and 35 modified fields that are used/applicable to Rosetta, but they required minimal if any changes to the Rosetta code base. @mariano, does that sound correct to you?

### Details:

- CIP 25: Ed25519 Precompile --> shouldn't affect rosetta (also backwards compatible)
- CIP 31: BLS Curve Operations on 12-381 --> don't think this should affect rosetta (also backwards compatible)
- CIP 30: BLS Curve Operations on 12-377 --> don't think this should affect rosetta (also backwards compatible)
- CIP 20: Extensible Hash Function Precompile --> shouldn't affect rosetta
- CIP 21: Governable Lookback Window --> don't think this should have affect rosetta
- CIP 22: Epoch Snark Data --> don't think this should affect rosetta (relevant to validators not full nodes)
- CIP 26: Precompile for BLS --> shouldn't affect rosetta
- CIP 28: Split etherbase --> looked into this: since `core` rosetta doesn't deal with Validator rewards (cUSD) anyways, this shouldn't be an issue there, and gas fees going to the `coinbase` address is still correct going forwards (`coinbase`==`txFeeRecipient`). For `rosetta-cusd`, this should also be fine since the address that appears in the Transfer event logs should continue to be correct (`validator` address)
- CIP 35: Support for Ethereum-compatible transactions --> changes are minimal; since we already use `celo-blockchain/core/types.NewTransaction` internally in Rosetta, no logic changes needed to be made.

### Done:
- updated kliento: branch `eelanagaraj/donut-preparation` (based on Trevor's rename branch :praise: but set to the updated blockchain branch)
- updated rosetta-master: branch `eelanagaraj/donut-preparation` (updated versions of kliento + blockchain, got it to compile, some testing via CLI and manually done)
- updated rosetta-beta/construction: `beta/construction-donut-preparation` (updated versions of kliento + blockchain, got it to compile, some testing via CLI (mainly Construction) and manually done)
- updated rosetta-cusd: branch `eelanagaraj/donut-preparation` (now uses `beta/construction-donut-preparation` branch, updated `celo-blockchain` module name + kliento/blockchain dep; CLI Construction tests and minimal data API tests)

### TODOs [punt until donut is on alfajores]:
- after donut changes are finalized, add any additional changes that have been added and test
- full CLI Data API checks once alfajores has hard forked for rosetta and rosetta-cusd
