### ISSUE TITLE
Celo Rosetta Node not responding to specific transaction hashes

### ISSUE THREAD

**Issue by debasish22** [celo-org/rosetta#184]
I am able to fetch the transactions for a block but one of the hashes of a particular block not able to retrieve the transactions from the rosetta node but when i checked on explorer transactions are present for that particular hash. I have got this issue for many hashes. Can any one help me here .

sudo curl --location --request POST 'localhost:8080/block/transaction' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "celo",
        "network": "42220"
    },
 "block_identifier": {
        "index": 8833070,
        "hash": "0xa813142f08eea79684b783cda31cc44f15f2c1d672fb728cf199f0c70b510123"
    },
 "transaction_identifier": {
        "hash": "0x072ac39955b78cb86624c1c5e33bd7707ca6d7ea3ec1592bd07311eb8745145d"
    }
}'

![Hash-NotFound_8969423](https://user-images.githubusercontent.com/30689502/152489968-fbc9cef8-9450-46c7-bbed-8dea9b5f7113.png)

**Comment by piersy** [comment]
Hi @debasish22 that is likely due to the blockchain node having pruned the state required for calculating the gas price for that transaction. Prior to [this PR](https://github.com/celo-org/celo-blockchain/pull/1818) trying to retrieve a transaction where required state had been pruned would result in an error and no transaction would be returned.Subsequent to that PR if the state required to calculate the gas price is missing  we will return the transaction but the gas price field will be nil.

If you require the gas price field to be present in returned transactions then you will either need to use an archive (`--gcmode=archive`)blockchain node (one that does not prune state) or ensure that you make your requests for the transactions before the state is pruned, only states for the last 128 blocks are stored for non archive nodes.

**Comment by debasish22** [comment]
@piersy Thanks for the inputs provided, Below are few of the details on our rosetta node

1. Our Rosetta node  version is 0.8.5 , will the next version be v1.5.3 which we can take and upgrade our celo node.
2. We dont require the gas price
3. After upgrading the rosetta node will we be able to query the hashes and get the information which we are not getting now  or we need to sync the data completely.
4.We are using the archive node for rosetta . Below is the command :

sudo docker run -d --name rosetta --rm \
  -v "$PWD:/data" -v "${PWD}/logs:/logs"\
  -p 8080:8080 \
  us.gcr.io/celo-testnet/rosetta:latest \
  run \
  --geth.syncmode full \
  --geth.gcmode archive

**Comment by eelanagaraj** [comment]
Closing this for now, please reopen if you continue to see issues with this from the next released version 🙏
